In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random as rd

In [53]:
ds = pd.read_csv(r"C:\Users\ANIKET\Downloads\AirQuality.csv", sep=";")

In [54]:
ds_heart = pd.read_csv(r"C:\Users\ANIKET\Downloads\heart.csv", sep=",")

In [55]:
ds.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN

In [56]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   object
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   object
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   object
 13  RH             9357 non-null   object
 14  AH             9357 non-null   object
 15  Unnamed: 15    0 non-null      float64
 16  Unnamed: 16    0 non-null      float64
dtypes: float64(10), object(7)
memory usage: 1.2+ MB

In [57]:
ds.isnull().sum()

Date              114
Time              114
CO(GT)            114
PT08.S1(CO)       114
NMHC(GT)          114
C6H6(GT)          114
PT08.S2(NMHC)     114
NOx(GT)           114
PT08.S3(NOx)      114
NO2(GT)           114
PT08.S4(NO2)      114
PT08.S5(O3)       114
T                 114
RH                114
AH                114
Unnamed: 15      9471
Unnamed: 16      9471
dtype: int64

In [58]:
ds.dropna()

Empty DataFrame
Columns: [Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH, Unnamed: 15, Unnamed: 16]
Index: []

In [59]:

ds.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [60]:
ds_heart.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [61]:
ds.columns = ds.columns.str.strip()

In [62]:
ds_heart.columns = ds_heart.columns.str.strip()

In [63]:
ds.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [64]:
ds1 = ds.loc[111:999, ['Date', 'Time', 'C6H6(GT)', 'RH']]
ds2 = ds.iloc[[1,3,5,2,4,22,43,54,67,7,8,9,50,10,11]]

In [65]:
print(ds.columns)

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [66]:
ds1 = ds.loc[111:999, ['Date', 'Time', 'C6H6(GT)', 'RH']]
ds2 = ds.iloc[[1,3,5,2,4,22,43,54,67,7,8,9,50,10,11]]

In [67]:
ds_integration = pd.concat([ds1,ds2])

In [68]:
ds_integration

,Date,Time,C6H6(GT),RH,CO(GT),PT08.S1(CO),NMHC(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,AH,Unnamed: 15,Unnamed: 16
111,15/03/2004,09.00.00,"36,7","54,3",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,15/03/2004,10.00.00,"26,6","45,6",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,15/03/2004,11.00.00,"20,1","38,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,15/03/2004,12.00.00,"14,1","34,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,15/03/2004,13.00.00,"14,9","32,2",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8,11/03/2004,02.00.00,"2,3","59,7","0,9",1094.0,24.0,609.0,45.0,1579.0,60.0,1276.0,620.0,"10,7","0,7648",NaN,NaN
9,11/03/2004,03.00.00,"1,7","60,2","0,6",1010.0,19.0,561.0,-200.0,1705.0,-200.0,1235.0,501.0,"10,3","0,7517",NaN,NaN
50,12/03/2004,20.00.00,"32,6","50,5","6,6",1843.0,488.0,1610.0,340.0,624.0,170.0,2390.0,1887.0,"12,9","0,7478",NaN,NaN
10,11/03/2004,04.00.00,"1,3","60,5",-200,1011.0,14.0,527.0,21.0,1818.0,34.0,1197.0,445.0,"10,1","0,7465",NaN,NaN
11,11/03/2004,05.00.00,"1,1","56,2","0,7",1066.0,8.0,512.0,16.0,1918.0,28.0,1182.0,422.0,"11,0","0,7366",NaN,NaN

In [69]:
ds_integration.transpose()

,111,112,113,114,115,116,117,118,119,120,...,22,43,54,67,7,8,9,50,10,11
Date,15/03/2004,15/03/2004,15/03/2004,15/03/2004,15/03/2004,15/03/2004,15/03/2004,15/03/2004,15/03/2004,15/03/2004,...,11/03/2004,12/03/2004,13/03/2004,13/03/2004,11/03/2004,11/03/2004,11/03/2004,12/03/2004,11/03/2004,11/03/2004
Time,09.00.00,10.00.00,11.00.00,12.00.00,13.00.00,14.00.00,15.00.00,16.00.00,17.00.00,18.00.00,...,16.00.00,13.00.00,00.00.00,13.00.00,01.00.00,02.00.00,03.00.00,20.00.00,04.00.00,05.00.00
C6H6(GT),"36,7","26,6","20,1","14,1","14,9","15,4","12,1","11,5","14,8","32,1",...,"8,3","11,0","9,6","12,3","3,3","2,3","1,7","32,6","1,3","1,1"
RH,"54,3","45,6","38,5","34,1","32,2","30,0","28,9","29,4","31,3","35,4",...,"71,2","34,5","64,1","31,3","60,0","59,7","60,2","50,5","60,5","56,2"
CO(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"2,2","2,5","2,7","2,8",1,"0,9","0,6","6,6",-200,"0,7"
PT08.S1(CO),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1292.0,1252.0,1280.0,1328.0,1136.0,1094.0,1010.0,1843.0,1011.0,1066.0
NMHC(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,95.0,140.0,122.0,154.0,31.0,24.0,19.0,488.0,14.0,8.0
PT08.S2(NMHC),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,912.0,1016.0,964.0,1059.0,672.0,609.0,561.0,1610.0,527.0,512.0
NOx(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,193.0,160.0,193.0,153.0,62.0,45.0,-200.0,340.0,21.0,16.0
PT08.S3(NOx),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1103.0,1008.0,963.0,987.0,1453.0,1579.0,1705.0,624.0,1818.0,1918.0
NO2(GT),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,131.0,116.0,113.0,124.0,76.0,60.0,-200.0,170.0,34.0,28.0
PT08.S4(NO2),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1591.0,1593.0,1544.0,1600.0,1333.0,1276.0,1235.0,2390.0,1197.0,1182.0
PT08.S5(O3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,957.0,983.0,1285.0,1101.0,730.0,620.0,501.0,1887.0,445.0,422.0
T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"9,7","16,1","9,5","19,4","10,7","10,7","10,3","12,9","10,1","11,0"
AH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"0,8569","0,6262","0,7597","0,6950","0,7702","0,7648","0,7517","0,7478","0,7465","0,7366"
Unnamed: 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unnamed: 16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
ds.drop(columns = "NOx(GT)")
ds2.drop(1)
ds.melt()

           variable       value
0              Date  10/03/2004
1              Date  10/03/2004
2              Date  10/03/2004
3              Date  10/03/2004
4              Date  10/03/2004
...             ...         ...
161002  Unnamed: 16         NaN
161003  Unnamed: 16         NaN
161004  Unnamed: 16         NaN
161005  Unnamed: 16         NaN
161006  Unnamed: 16         NaN

[161007 rows x 2 columns]

In [71]:
ds_merged = pd.concat([ds,ds_heart])
ds_merged

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),...,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TA,110.0,264.0,0.0,Normal,132.0,N,1.2,Flat,1.0
914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ASY,144.0,193.0,1.0,Normal,141.0,N,3.4,Flat,1.0
915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ASY,130.0,131.0,0.0,Normal,115.0,Y,1.2,Flat,1.0
916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ATA,130.0,236.0,0.0,LVH,174.0,N,0.0,Flat,1.0
917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NAP,138.0,175.0,0.0,Normal,173.0,N,0.0,Up,0.0

In [75]:
ds.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [77]:
ds['RH'].unique()

array(['48,9', '47,7', '54,0', '60,0', '59,6', '59,2', '56,8', '59,7',
       '60,2', '60,5', '56,2', '58,1', '57,4', '60,6', '58,4', '57,9',
       '66,8', '76,4', '81,1', '79,8', '71,2', '67,6', '64,2', '69,3',
       '67,8', '64,0', '63,4', '60,8', '58,5', '61,8', '62,3', '65,9',
       '65,0', '62,9', '65,1', '63,1', '41,7', '38,4', '36,5', '34,5',
       '35,7', '37,0', '37,2', '34,3', '39,6', '43,4', '50,5', '53,3',
       '59,1', '64,6', '64,1', '63,9', '67,5', '71,1', '63,6', '71,9',
       '71,6', '51,2', '42,2', '33,8', '31,3', '34,8', '33,6', '35,1',
       '37,8', '41,0', '42,4', '44,1', '46,8', '48,6', '49,3', '53,6',
       '51,5', '58,9', '61,1', '62,2', '62,7', '53,1', '46,1', '38,3',
       '31,4', '30,2', '29,0', '28,4', '30,8', '36,7', '49,6', '51,0',
       '55,9', '54,7', '57,0', '61,3', '63,5', '65,4', '67,4', '70,5',
       '70,2', '54,3', '45,6', '38,5', '34,1', '32,2', '30,0', '28,9',
       '29,4', '35,4', '42,5', '52,6', '61,4', '65,7', '62,1', '66,2',
       '63,2', '68,5', '66,5', '63,7', '56,3', '42,9', '33,3', '27,4',
       '26,1', '23,2', '20,2', '18,6', '19,1', '25,7', '41,3', '45,9',
       '52,9', '51,9', '55,6', '58,0', '65,2', '50,0', '40,1', '33,4',
       '28,3', '25,6', '25,9', '18,7', '15,8', '14,9', '16,0', '26,5',
       '38,2', '42,6', '50,9', '53,9', '55,4', '52,1', '61,9', '63,3',
       '50,6', '40,5', '34,4', '28,2', '28,7', '24,9', '17,8', '23,1',
       '23,9', '26,8', '31,1', '36,2', '48,4', '57,8', '69,7', '67,7',
       '66,3', '64,9', '61,6', '58,8', '57,1', '54,4', '50,1', '47,6',
       '47,1', '47,5', '50,2', '50,7', '50,3', '51,4', '57,6', '58,3',
       '55,1', '54,6', '59,0', '52,3', '47,9', '42,3', '43,8', '46,3',
       '51,6', '51,3', '53,8', '57,7', '58,6', '60,9', '56,6', '63,0',
       '65,3', '41,6', '40,3', '39,3', '38,0', '48,1', '46,9', '49,1',
       '51,7', '53,7', '42,1', '29,6', '28,1', '24,2', '28,5', '43,1',
       '47,4', '49,7', '52,0', '49,4', '70,0', '76,8', '80,5', '75,4',
       '75,0', '74,2', '55,8', '54,8', '53,4', '49,8', '49,5', '58,2',
       '54,2', '54,9', '62,5', '57,2', '57,3', '56,9', '44,3', '40,6',
       '34,6', '35,6', '69,1', '67,3', '66,9', '59,9', '68,1', '68,2',
       '72,3', '83,2', '79,0', '74,6', '75,1', '64,4', '53,0', '37,4',
       '47,8', '52,5', '53,2', '56,1', '59,5', '62,6', '69,4', '72,4',
       '71,8', '35,3', '27,1', '26,2', '36,8', '43,3', '48,0', '51,1',
       '50,8', '50,4', '64,8', '66,6', '36,1', '29,2', '30,1', '28,6',
       '26,0', '44,9', '66,7', '66,4', '68,0', '36,9', '26,4', '25,0',
       '27,3', '35,0', '40,2', '43,2', '46,5', '46,6', '45,8', '37,6',
       '33,2', '27,9', '37,9', '31,9', '38,7', '33,9', '28,8', '26,6',
       '22,5', '20,0', '21,7', '30,6', '34,7', '40,4', '42,0', '43,5',
       '44,6', '40,8', '36,0', '74,4', '71,0', '73,3', '78,1', '69,2',
       '59,3', '56,0', '67,2', '73,1', '68,8', '69,6', '-200', '27,5',
       '32,1', '40,9', '44,0', '64,3', '72,9', '73,7', '30,5', '22,8',
       '22,3', '43,0', '47,0', '51,8', '61,7', '35,8', '27,0', '56,5',
       '62,4', '40,7', '37,1', '61,5', '56,7', '55,2', '42,8', '45,4',
       '41,8', '36,6', '44,4', '48,7', '71,3', '74,0', '75,2', '76,0',
       '76,7', '79,6', '80,6', '75,6', '72,1', '70,4', '34,2', '26,7',
       '22,6', '24,8', '25,4', '24,5', '32,9', '39,8', '41,5', '46,0',
       '67,9', '70,1', '69,8', '70,3', '73,4', '22,7', '21,3', '31,6',
       '55,5', '66,0', '70,7', '22,9', '22,4', '18,9', '19,0', '23,6',
       '37,5', '39,0', '34,0', '32,8', '30,9', '43,6', '61,2', '60,1',
       '68,4', '68,7', '42,7', '38,1', '54,1', '63,8', '65,8', '65,6',
       '30,4', '58,7', '35,5', '74,8', '75,3', '46,7', '75,7', '77,4',
       '74,9', '76,3', '78,0', '79,4', '80,1', '81,0', '81,8', '81,2',
       '82,4', '79,9', '80,0', '80,8', '61,0', '45,7', '49,9', '52,8',
       '72,7', '77,2', '74,5', '60,4', '78,3', '78,2', '70,9', '45,5',
       '71,5', '77,5', '77,7', '80,2', '79,7', '78,9', '26,9', '29,9',
       '39,5', '45,0', '22,2', '20,5', '24,1', '33,7', '53,5', '24,4',
       '21,0', '16,4', '16,2', '24,3', '29,5', '38,8', '43,7', '52,2',
       '31,0', '20,6', '21,5', '20,1', '19,4', '55,3', '32,4', '31,8',
       '39,7', '73,5', '76,9', '43,9', '38,6', '30,7', '27,2', '27,8',
       '30,3', '45,3', '32,3', '31,7', '32,5', '32,7', '35,9', '41,4',
       '47,3', '48,5', '29,1', '25,3', '22,0', '20,4', '23,8', '22,1',
       '44,7', '60,7', '46,4', '23,4', '37,3', '67,0', '25,5', '78,6',
       '78,4', '78,5', '74,7', '73,2', '66,1', '68,3', '69,9', '67,1',
       '62,0', '31,5', '33,5', '38,9', '56,4', '36,4', '68,9', '25,2',
       '19,7', '39,4', '79,2', '70,8', '55,7', '62,8', '64,5', '74,1',
       '77,1', '68,6', '72,5', '75,8', '72,2', '37,7', '54,5', '65,5',
       '64,7', '27,7', '29,7', '85,2', '81,5', '60,3', '73,8', '44,8',
       '55,0', '59,8', '32,0', '35,2', '29,8', '31,2', '52,4', '47,2',
       '57,5', '20,8', '21,6', '21,9', '25,1', '23,5', '21,1', '45,1',
       '19,8', '24,6', '36,3', '27,6', '19,5', '17,1', '24,0', '40,0',
       '24,7', '49,2', '41,1', '26,3', '46,2', '25,8', '23,3', '19,3',
       '20,3', '23,7', '41,9', '48,3', '29,3', '41,2', '45,2', '18,1',
       '17,0', '16,1', '14,5', '13,1', '12,9', '14,0', '15,4', '17,2',
       '13,0', '9,9', '9,8', '9,2', '9,3', '10,0', '10,7', '12,2', '13,3',
       '13,5', '13,8', '15,9', '28,0', '20,9', '33,0', '34,9', '44,2',
       '20,7', '19,6', '18,4', '15,0', '39,9', '81,6', '80,3', '82,3',
       '81,3', '80,9', '69,0', '49,0', '32,6', '59,4', '52,7', '79,1',
       '39,2', '19,9', '44,5', '17,7', '17,4', '18,3', '15,3', '14,2',
       '16,7', '18,8', '48,2', '18,2', '16,6', '15,1', '14,7', '21,8',
       '39,1', '21,4', '18,0', '18,5', '15,5', '17,5', '12,8', '11,9',
       '23,0', '15,2', '16,8', '14,8', '15,6', '12,7', '13,4', '17,3',
       '16,9', '13,9', '13,2', '12,6', '17,9', '9,6', '10,2', '11,6',
       '33,1', '15,7', '14,6', '19,2', '48,8', '13,6', '13,7', '14,3',
       '16,5', '16,3', '12,3', '11,8', '12,5', '14,4', '78,8', '72,6',
       '72,8', '75,5', '75,9', '10,9', '21,2', '17,6', '72,0', '82,5',
       '87,2', '77,8', '76,2', '74,3', '73,9', '76,6', '69,5', '77,3',
       '83,8', '84,6', '77,6', '81,9', '82,9', '80,4', '80,7', '82,1',
       '73,6', '71,7', '73,0', '70,6', '71,4', '76,1', '77,9', '77,0',
       '78,7', '86,5', '82,2', '79,3', '81,4', '76,5', '85,7', '85,6',
       '83,5', '84,8', '86,0', '87,1', '81,7', '83,4', '82,6', '83,6',
       '84,3', '84,1', '83,0', '84,0', '85,4', '84,4', '83,1', '83,7',
       '84,2', '82,8', '82,7', '85,1', '85,5', '85,3', '84,5', '83,9',
       '88,7', '87,0', '83,3', '86,6', '85,0', '79,5', '82,0', '11,1',
       '10,4', nan], dtype=object)

In [78]:
ds.RH.value_counts()

RH
-200    366
53,1     31
47,8     30
57,9     30
45,9     27
       ...
85,2      1
87,2      1
84,2      1
11,1      1
10,4      1
Name: count, Length: 754, dtype: int64